spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fhvghdtfgtjrmmdnoqyr
spring.datasource.password=gYJ?&Ej#QP)cQ3h
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=schooltable111@gmail.com
spring.mail.password=dghi lksu zvje zyqi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

telegram.bot.token=8887495231:AAHp4Iwv61G_h-aZNnNzwu2WClzCcIc5R3g
telegram.admin.chatId=5103255947
telegram.webhook.secret=mySuperSecret_9f3k2Lx8pQ

server.port=${PORT:8080}
resend.api.key=${RESEND_API_KEY}
resend.from.email=onboarding@resend.dev