spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.admin.chatId=${TELEGRAM_ADMIN_CHAT_ID}
telegram.webhook.secret=${TELEGRAM_WEBHOOK_SECRET}

server.port=${PORT:8080}
resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}

jwt.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true